# Generated by Django 4.0.4 on 2022-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(1, 'review'), (2, 'blocked'), (3, 'correct')], default='review')),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
