# Generated by Django 4.0.4 on 2022-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, 'review'), (2, 'blocked'), (3, 'correct')], default=1),
        ),
    ]
