version: '3.8'

volumes:
  pgdata-api:

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testapi
    volumes:
      - pgdata-api:/var/lib/postgresql/data
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  web:
    container_name: test-api
    build: ../TestProject/
    restart: always
    env_file:
      - ../TestProject/envs/.env
    ports:
      - 8000:8000
    links:
      - postgres
      - zookeeper
      - kafka